apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-y3ct
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-y3ct
    app.kubernetes.io/part-of: tkwch-fix-0075-0011-app
  name: devfile-sample-y3ct
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-y3ct
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-y3ct
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0011-tenant/tkwch-fix-0075-0011-app/devfile-sample-y3ct@sha256:5879f5adbd8e305d9eadbe8b97e105829e92ab92293a86e1572f9db1ca1a22e8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
